#ifndef __DEFINITIONS_H__
#define __DEFINITIONS_H__

#define DISPLAY_TIME_SPLASH_SCENE 2
#define TRANSITION_TIME 0.5

#define PLAYER_COLLISION_BITMASK 0x000001
#define BOMB_COLLISION_BITMASK 0x000002


#endif // __DEFINITIONS_H__
